#!/bin/bash

source /etc/environment
ps -ef | grep "$FLUME_HOME" | grep -v grep | awk '{print $2}' | xargs kill -9
sleep 5
su flume -c "nohup $FLUME_HOME/bin/flume-ng agent -c $FLUME_CONF_DIR -f $FLUME_CONF_DIR/flume.conf -n a1 &"
sleep 10
